const products = [
  {
    name: "Free Shirt",
    categories: ["shirts", "men"],
    img: "/images/shirt1.jpg",
    price: 70,
    brand: "Nike",
    rating: 4.5,
    numReviews: 8,
    countInStock: 20,
    desc: "A popular shirt",
    size: ["M", "S"],
    color: ["Black", "Green", "Blue"],
  },
  {
    name: "Fit Shirt",
    categories: ["Shirts", "women"],
    img: "/images/shirt2.jpg",
    price: 80,
    brand: "Adidas",
    rating: 3.2,
    numReviews: 10,
    countInStock: 20,
    desc: "A popular shirt",
    size: ["M", "L"],
    color: ["Black", "White", "Red"],
  },
  {
    name: "Slim Shirt",
    categories: ["Shirts", "men"],
    img: "/images/shirt3.jpg",
    price: 90,
    brand: "Raymond",
    rating: 4.5,
    numReviews: 3,
    countInStock: 20,
    desc: "A popular shirt",
    size: ["S", "L"],
    color: ["Red", "Green", "Blue"],
  },
  {
    name: "Golf Pants",
    categories: ["Pants", "men"],
    img: "/images/pants1.jpg",
    price: 90,
    brand: "Oliver",
    rating: 2.9,
    numReviews: 13,
    countInStock: 20,
    desc: "Smart looking pants",
    size: ["L"],
    color: ["Black", "Green", "Blue"],
  },
  {
    name: "Fit Pants",
    categories: ["Pants", "women"],
    img: "/images/pants2.jpg",
    price: 95,
    brand: "Zara",
    rating: 3.5,
    numReviews: 7,
    countInStock: 20,
    desc: "A popular pants",
    size: ["M"],
    color: ["Black", "White", "Red"],
  },
  {
    name: "Classic Pants",
    desc: "A popular pants",
    img: "/images/pants3.jpg",
    categories: ["Pants", "men"],
    size: ["S"],
    color: ["White", "Red", "Blue"],
    price: 75,
    brand: "Casely",
    rating: 2.4,
    numReviews: 14,
    countInStock: 20,
  },
];


module.exports = {products}